general {
  lock_cmd = hyprlock
  before_sleep_cmd = loginctl lock-session
  after_sleep_cmd = hyprctl eval 'hl.monitor({ output = "eDP-1", disabled = false })'
}

listener {
  timeout = 300
  on-timeout = hyprlock
}
